# Generated by Django 5.0.6 on 2024-06-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
