# Generated by Django 5.0.6 on 2024-06-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0002_alter_sign_up_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_up',
        ),
    ]
