# Generated by Django 5.0.6 on 2024-06-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign_up',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='sign_up',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sign_up',
            name='password',
        ),
    ]
