# Generated by Django 5.0.6 on 2024-06-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0009_remove_sign_up_confirm_password_remove_sign_up_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up',
            old_name='first_name',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='sign_up',
            old_name='last_name',
            new_name='last',
        ),
    ]
