# Generated by Django 5.0.6 on 2024-06-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0010_rename_first_name_sign_up_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
