# Generated by Django 5.0.6 on 2024-06-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0011_sign_up_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_up',
        ),
    ]
