# Generated by Django 5.0.6 on 2024-06-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0014_alter_sign_up_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign_up',
            name='confirm_password',
        ),
    ]
