# Generated by Django 5.0.6 on 2024-06-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0015_remove_sign_up_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
