# Generated by Django 5.0.6 on 2024-06-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0017_alter_sign_up_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign_Up',
        ),
    ]
