# Generated by Django 5.0.6 on 2024-06-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0023_sign_up'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Sign_Up',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
