# Generated by Django 5.0.6 on 2024-07-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_', '0024_delete_employee_delete_sign_up_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('profile_photo', models.ImageField(upload_to='images/')),
                ('location', models.CharField(max_length=40)),
                ('blood_group', models.CharField(max_length=1)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
