# Generated by Django 5.0.6 on 2024-07-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0025_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
