# Generated by Django 5.0.6 on 2024-07-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0026_alter_signup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='blood_group',
            field=models.CharField(max_length=2),
        ),
    ]
