# Generated by Django 5.0.6 on 2024-07-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0027_alter_signup_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
