# Generated by Django 5.0.6 on 2024-07-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0029_signup_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='User',
        ),
    ]
