# Generated by Django 5.0.6 on 2024-07-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0030_rename_signup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
