# Generated by Django 5.0.6 on 2024-07-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0031_user_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='SignUp',
        ),
    ]
