# Generated by Django 5.0.6 on 2024-07-09 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0036_remove_signup_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
