# Generated by Django 5.0.6 on 2024-07-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0037_currentdatetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentDateTime',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
