# Generated by Django 5.0.6 on 2024-07-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0038_delete_currentdatetime_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('Hospital_name_location', models.CharField(max_length=20, null=True)),
                ('patients_department', models.CharField(max_length=120)),
                ('patients_phone', models.IntegerField(blank=True, null=True)),
                ('blood_pint', models.IntegerField(null=True)),
                ('patients_blood_group', models.CharField(max_length=10, null=True)),
                ('requisition_form', models.ImageField(upload_to='patientsForm/')),
            ],
        ),
    ]
