# Generated by Django 5.0.6 on 2024-07-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0039_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Hospital_name_location',
            new_name='hospital_name_location',
        ),
    ]
