# Generated by Django 5.0.6 on 2024-07-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0041_rename_hospital_name_location_patient_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
