# Generated by Django 5.0.6 on 2024-07-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0043_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
