# Generated by Django 5.0.6 on 2024-07-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0044_remove_signup_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='weight',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
