# Generated by Django 5.0.6 on 2024-07-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0045_signup_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
