# Generated by Django 5.0.6 on 2024-07-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0046_alter_signup_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
