# Generated by Django 5.0.6 on 2024-07-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0048_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
