# Generated by Django 5.0.6 on 2024-07-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0051_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
