# Generated by Django 5.0.6 on 2024-07-18 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0052_delete_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=20, null=True)),
                ('patients_department', models.CharField(max_length=120)),
                ('patients_phone', models.IntegerField(blank=True, null=True)),
                ('blood_pint', models.IntegerField(null=True)),
                ('patients_blood_group', models.CharField(max_length=10, null=True)),
                ('requisition_form', models.ImageField(upload_to='patientsForm/')),
                ('signup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_.signup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
