# Generated by Django 5.0.6 on 2024-07-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0053_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='signup',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
