# Generated by Django 5.0.6 on 2024-07-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0054_remove_patient_signup_remove_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='full_name',
            new_name='Patient_full_name',
        ),
    ]
