# Generated by Django 5.0.6 on 2024-07-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0056_rename_patient_full_name_patient_patients_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Patients_full_name',
            new_name='full_name',
        ),
    ]
