# Generated by Django 5.0.6 on 2024-07-18 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0057_rename_patients_full_name_patient_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='signup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_.signup'),
        ),
    ]
