# Generated by Django 5.0.6 on 2024-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0062_alter_signup_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='available',
            field=models.BooleanField(null=True),
        ),
    ]
