# Generated by Django 5.0.6 on 2024-08-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0063_signup_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='available',
            new_name='ready_to_donate',
        ),
    ]
