# Generated by Django 5.0.6 on 2024-08-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0066_alter_signup_ready_to_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='gender',
            field=models.CharField(max_length=4),
        ),
    ]
