# Generated by Django 5.0.6 on 2024-08-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0067_alter_signup_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_pint',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patients_blood_group',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patients_phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='blood_group',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='weight',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
