# Generated by Django 5.0.6 on 2024-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0069_alter_patient_blood_pint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
