# Generated by Django 5.0.6 on 2024-08-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0071_alter_signup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
