# Generated by Django 5.0.6 on 2024-08-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0073_alter_signup_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='last_donation',
            field=models.DateField(null=True),
        ),
    ]
