# Generated by Django 5.0.6 on 2024-08-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0074_signup_last_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
