# Generated by Django 5.0.6 on 2024-08-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0077_patient_patients_gender_patient_required_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='ready_to_donate',
            field=models.BooleanField(null=True),
        ),
    ]
