# Generated by Django 5.0.6 on 2024-08-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0078_alter_signup_ready_to_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='signup',
            name='ready_to_donate',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=4, null=True),
        ),
    ]
