# Generated by Django 5.0.6 on 2024-08-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0080_alter_patient_patients_blood_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='signup',
            new_name='RequestedBy',
        ),
    ]
