# Generated by Django 5.0.6 on 2024-08-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0081_rename_signup_patient_requestedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='RequestedBy',
            new_name='signup',
        ),
    ]
