# Generated by Django 5.0.6 on 2024-08-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0083_rename_signup_patient_requested_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='requested_by',
            new_name='blood_requested_by',
        ),
    ]
