# Generated by Django 5.0.6 on 2024-08-12 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0084_rename_requested_by_patient_blood_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_requested_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_received', to='profile_.signup'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_made', to='profile_.signup'),
        ),
    ]
