# Generated by Django 5.0.6 on 2024-08-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0085_patient_blood_requested_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='full_name',
            new_name='patients_name',
        ),
    ]
