# Generated by Django 5.0.6 on 2024-08-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0088_alter_patient_blood_requested_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='ready_to_donate',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True),
        ),
    ]
