# Generated by Django 5.0.6 on 2024-08-16 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0089_alter_signup_ready_to_donate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_requested_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_requested_to',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_request_received',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received', to='profile_.signup'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_requested_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent', to='profile_.signup'),
        ),
    ]
