# Generated by Django 5.0.6 on 2024-08-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0091_rename_blood_requested_sent_patient_blood_request_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='blood_request_received',
            new_name='blood_request_received_from',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='blood_request_sent',
            new_name='blood_request_sent_by',
        ),
    ]
