# Generated by Django 5.0.6 on 2024-08-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0094_alter_patient_required_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='required_date',
            field=models.DateField(null=True),
        ),
    ]
