# Generated by Django 5.0.6 on 2024-08-27 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0098_patient_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='msg',
        ),
        migrations.AddField(
            model_name='patient',
            name='msg_sent_by',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_by', to='profile_.signup'),
        ),
        migrations.AddField(
            model_name='patient',
            name='msg_sent_to',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_to', to='profile_.signup'),
        ),
    ]
