# Generated by Django 5.0.6 on 2024-08-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0100_remove_patient_msg_sent_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='msg',
            new_name='message',
        ),
    ]
