# Generated by Django 5.0.6 on 2024-08-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0101_rename_msg_patient_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patients_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
