# Generated by Django 5.0.6 on 2024-08-27 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0104_message_remove_patient_reply_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_sent_by', to='profile_.signup'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_sent_to', to='profile_.signup'),
        ),
    ]
