# Generated by Django 5.0.6 on 2024-09-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0107_alter_signup_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table="User's Signup data",
        ),
    ]
