# Generated by Django 5.0.6 on 2024-09-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0108_alter_signup_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table=None,
        ),
    ]
