# Generated by Django 5.0.6 on 2024-09-05 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0109_alter_signup_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_request_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_by', to='profile_.signup'),
        ),
    ]
