# Generated by Django 5.0.6 on 2024-09-05 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0110_alter_patient_blood_request_sent_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_request_sent_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_to', to='profile_.signup'),
        ),
    ]
