# Generated by Django 5.0.6 on 2024-09-05 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0111_alter_patient_blood_request_sent_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCopy',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profile_.patient')),
            ],
            bases=('profile_.patient',),
        ),
    ]
