# Generated by Django 5.0.6 on 2024-09-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0112_patientcopy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientCopy',
        ),
    ]
