# Generated by Django 5.0.6 on 2024-09-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0114_alter_patient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
    ]
