# Generated by Django 5.0.6 on 2024-09-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0118_alter_message_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='message',
            index_together=set(),
        ),
    ]
