# Generated by Django 5.0.6 on 2024-09-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0120_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
