# Generated by Django 5.0.6 on 2024-07-19 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('author', models.CharField(max_length=30, verbose_name='author')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('content', models.TextField(verbose_name='content')),
            ],
        ),
    ]
