# Generated by Django 5.0.6 on 2024-07-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogmodel',
            new_name='Blog',
        ),
    ]
