# Generated by Django 5.0.6 on 2024-07-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_blogmodel_blog'),
        ('profile_', '0058_patient_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_.signup'),
        ),
    ]
