# Generated by Django 5.0.6 on 2024-07-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='sign',
            new_name='signup',
        ),
    ]
