# Generated by Django 5.0.6 on 2024-07-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_sign_blog_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
